### ISSUE TITLE
[Feature] Design Page

### ISSUE THREAD

**Issue by DVergil** [redphx/better-xcloud#154]
**I'm using:**  
- Device: Android
- OS: Android TV
- Browser: Kiwi
  
**I want to suggest this feature:**  

Choose the design of the xcloud page from other platforms such as Tizen, Windows, IOS

**Comment by KingNothing81** [comment]
You can achieve this by changing user-agent profile in the advanced settings. But I think the xCloud webpage almost looks identical on all platforms. Maybe with the most evident difference if you use the Samsung Smart TV profile.

Or do you want to mimic the look of the Game Pass App?

**Comment by KingNothing81** [comment]
@DVergil: I know this is the bug tracker, not the discussion area. But as I see that you are also using "Better xCloud" with Kiwi on Android TV, I hope @redphx and others don't mind asking you what controller you use or can recommend?

Because I have some problems finding a controller that works without issues when playing games in the web browser. At the moment I use my old Shield controller and tried out the Moga XP5-X recently. But with both I have the problem that the button that is supposed to be the select button behaves like a back button in Kiwi browser. So I have to use the "External Keyboard Helper" app to remap it.

So what controller out there would work out of the box without those mapping issues?
Thanks and sorry for hijacking that post.

**Comment by redphx** [comment]
@DVergil added in version 2.0  

@KingNothing81 I use an 8bit SN30 Pro (AYANEO version) and it works fine on Android 12.  
X-Input doesn't work well on Android browsers. I think you'll need a controller with D-Input. If your device support Switch Pro controllr then it's also good.

**Comment by DVergil** [comment]
Thanks

**Comment by KingNothing81** [comment]
> @KingNothing81 I use an 8bit SN30 Pro (AYANEO version) and it works fine on Android 12. X-Input doesn't work well on Android browsers. I think you'll need a controller with D-Input. If your device support Switch Pro controllr then it's also good.

@redphx: The Moga XP5-X should use D-Input in wireless mode. And is even certified by Microsoft to be used for xCloud. But using it on my Shield TV (Android TV 11) and as long as you are not in a real game app, but use it in Kiwi browser, the Select button will act like a Back button and the middle Xbox button like a Home button, So both kick me out to the games. So as mentioned, I'm back using my Shield controller. But have to use "External Keyboard Helper" to remap the Back/Select button. Because for unknown reasons, using an app like "Button Mapper", the remapping is not recognized in-game when using xCloud.

But my problems might also be related to some button remapping done by Nvidia on a OS level and/or the fact that the device still runs Android 11. So I have some doubt that they would be resolvable with another controller.

**Comment by DVergil** [comment]
My control even works the xbox button to open the menu within the game currently

**Comment by DVergil** [comment]
I currently play on an amazon fire stick using the control's usb receiver

**Comment by KingNothing81** [comment]
>My control even works the xbox button to open the menu within the game currently
> I currently play on an amazon fire stick using the control's usb receiver

Yeah ... I saw a video on Youtube where a guy was also able to make the middle button on a Gamesir controller work as expected (open the Xbox sidebar) by plugging in the USB receiver instead of connecting directly via bluetooth. So I guess that might make a difference. But my Shield controller has no additional USB dongle.

There is rumor that Microsoft will release a new Xbox controller soon, that will also support a direct connection to the cloud. Like the Luna and Stadia controller. Directly connected to the cloud, there shouldn't be any of those mapping problems. So I guess if I will get a new controller, it will be one of those.

**Comment by DVergil** [comment]
Will you need to spend some money to buy a new control?

**Comment by DVergil** [comment]
I would buy a usb hub and connect it through the dongle

**Comment by DVergil** [comment]
I strongly recommend taking any control from 8bitdo, I saw people using them on fire sticks and it worked all the buttons even via bluetooth

**Comment by KingNothing81** [comment]
> I would buy a usb hub and connect it through the dongle

I think my Nvidia Shield controller actually uses Wifi-Direct. So it won't work with a generic bluetooth dongle. So it would be easier to just buy a controller that comes bundled with an USB dongle. 

But at the moment I will continue to use my old controller. Because at least it has a very long battery life. And in the future I might get one of those new Xbox controllers that support cloud-direct technology.

 https://www.theverge.com/2023/9/19/23880809/microsoft-xbox-leak-gamepad-sebile-stadia-steam-sony

But thanks for your feedback but let's not make @redphx angry by having a discussion in the bug tracker. ;)

**Comment by DVergil** [comment]
Yes, have a great day.
