### ISSUE TITLE
[Bug] menu button Xbox controller exits game 

### ISSUE THREAD

**Issue by Ckleinloog** [redphx/better-xcloud#177]
**Platform**
 - Device: NVIDIA shield pro
 - OS: Android
 - Browser: Kiwi browser
 - Browser Version:
 - Better xCloud Version: 

**Describe the bug**

one small bug on my setup is that the map button on xbox controller does not work in-game, like FH4. instead of opening the world map in FH4, pressing the map button exits the game and lands me back on xbox/play site in kiwi browser. Is that a setting I can change or is it a bug in my setup? the controller and map button works fine using xcloud android app. 

Cheers.

**Screenshots/Videos**
If applicable, add screenshots/videos to help explain your problem.

**Comment by redphx** [comment]
Does it work when Better xCloud is disabled?  
Do you have the "Enable controller shortcuts" option on?

**Comment by KingNothing81** [comment]
> one small bug on my setup is that the map button on xbox controller does not work in-game, like FH4. instead of opening the world map in FH4, pressing the map button exits the game and lands me back on xbox/play site in kiwi browser. Is that a setting I can change or is it a bug in my setup? the controller and map button works fine using xcloud android app.
>
@Ckleinloog : It seems you are affected by the same issue I talked about here:
https://github.com/redphx/better-xcloud/issues/154#issuecomment-1826375467

Using xCloud with Kiwi on Android TV I'm seeing the same behaviour: The button that is supposed to work as the "Select/Menu" button, is acting like a "Back" button in Kiwi Browser. So it will kick you out of the game, back to the xCloud website. But the button works as expected when you are in "real" game app or the Game Pass Android app.

As I don't hear more people complain about this, this might be a problem specific to using xCloud in a web browser on the Shield TV (Android TV 11).

You can bypass this problem by remapping the button with the "External Keyboard Helper Pro" app and following this tuorial:
https://github.com/mistertest/xcloud-shield/wiki/1-Remapping-button-Back-Select-of-your-controller

But you won't have to download the app from that untrusted source, as "External Keyboard Helper Pro" is also available in the PlayStore. If you need further help to get this working, you can leave a message here.

**Comment by Ckleinloog** [comment]
> Does it work when Better xCloud is disabled? Do you have the "Enable controller shortcuts" option on?

Sorry, turns out it's Kiwi browser. Tried with script disabled and same issue with Map button.

**Comment by Ckleinloog** [comment]
@KingNothing81 
Thank you for that info. 
I can confirm it's Kiwi browser issue, not your extension. 
Surprised this issue has not popped up more in the forum's. As I thought the shield user would be your biggest users base for the extension.

**Comment by KingNothing81** [comment]
> @KingNothing81 Thank you for that info. I can confirm it's Kiwi browser issue, not your extension. Surprised this issue has not popped up more in the forum's. As I thought the shield user would be your biggest users base for the extension.

@Ckleinloog: Actually it’s also not really an issue with Kiwi browser. Because before starting using it, I also tried out other web browsers. Like sideloaded Chrome and some of the web browsers directly available to install on the Shield TV  via PlayStore. And I had this problem with all of them.

My guess is that Nvidia is doing some internal button remapping here. Because their Shield controllers don’t have a dedicated “Select” button. Just a “Back” button that acts like “Select” when you are in a real Android game or use GFN. But in a web browser, the button will continue to act like “Back”. 

And now it seems that this affects all controllers connected to Shield TV. I guess over at NVIDIA nobody thought about that one day people will start using web browsers to use cloud gaming services on Shield TV that are not officially supported on Android TV. But thanks for reporting this. Now I know that even buying a Xbox controller won’t help me avoid this issue.

**Comment by redphx** [comment]
Have you tried using the Button Mapper app to disable the feature of this button?

**Comment by Ckleinloog** [comment]
I have button mapper installed to remap the netflix button on my shield remote.
Do you have instructions how to change the behavior of the back button on Xbox controller using Button Mapper?
Cheers.


________________________________

**Comment by redphx** [comment]
> I have button mapper installed to remap the netflix button on my shield remote. Do you have instructions how to change the behavior of the back button on Xbox controller using Button Mapper? Cheers.
> […](#)

Add buttons > press Map button > Single Press = No action

**Comment by Ckleinloog** [comment]
Setting No Action works. Browser doesn't close anymore but this also removes the function of button in game. As in, it doesn't open the world map in FH4 etc.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by redphx** [comment]
I'll close this issue as it's not related to Better xCloud, but you can still discuss.

**Comment by hfrrrr** [comment]
It's related to NVIDIA custom configuration (hooks) for remote and gamepad.

Disable this package and welcome to perfect gamepass experience :

adb shell pm disable-user com.nvidia.shieldtech.hooks

**Comment by Ckleinloog** [comment]
Awesome, this is the solution. And now the white X button also works and pulls up the menu to exit game. Thank very much for sharing. Much appreciated.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by KingNothing81** [comment]
> I have button mapper installed to remap the netflix button on my shield remote. Do you have instructions how to change the behavior of the back button on Xbox controller using Button Mapper? Cheers.

@Ckleinloog:  I tried various button mapper apps, including "Button Mapper". But first of all, the option to remap to gamepad buttons is missing in all of them. Some let you remap to a certain keycode. So I looked it up and tried remapping to it with the Pro version of "Button Mapper". But the remapping is not recognized within the game running on xCloud. So the only app I found working is the "External Keyboard Helper Pro" app.

> It's related to NVIDIA custom configuration (hooks) for remote and gamepad.
> 
> Disable this package and welcome to perfect gamepass experience :
> 
> adb shell pm disable-user com.nvidia.shieldtech.hooks

@hfrrrr: That's a great tip. But I guess this will also disable things like the ability to long press Back to bring up the quick settings? Will this have negative impact when using their own GFN? If I want to revert this, what would be the command? Will it be just "enable" instead of "disable" in the given line? Thank you.

**Comment by Ckleinloog** [comment]
@KingNothing81 I recently found ADB TV on the playstore. Very user friendly to disable/ enable commands.

**Comment by hfrrrr** [comment]
> > I have button mapper installed to remap the netflix button on my shield remote. Do you have instructions how to change the behavior of the back button on Xbox controller using Button Mapper? Cheers.
> 
> @Ckleinloog: I tried various button mapper apps, including "Button Mapper". But first of all, the option to remap to gamepad buttons is missing in all of them. Some let you remap to a certain keycode. So I looked it up and tried remapping to it with the Pro version of "Button Mapper". But the remapping is not recognized within the game running on xCloud. So the only app I found working is the "External Keyboard Helper Pro" app.
> 
> > It's related to NVIDIA custom configuration (hooks) for remote and gamepad.
> > Disable this package and welcome to perfect gamepass experience :
> > adb shell pm disable-user com.nvidia.shieldtech.hooks
> 
> @hfrrrr: That's a great tip. But I guess this will also disable things like the ability to long press Back to bring up the quick settings? Will this have negative impact when using their own GFN? If I want to revert this, what would be the command? Will it be just "enable" instead of "disable" in the given line? Thank you.

To enable again package run command

adb shell pm enable com.nvidia.shieldtech.hooks
