### ISSUE TITLE
[Bug] Cannot play anything other than Fortnite

### ISSUE THREAD

**Issue by NasiWaarteG** [redphx/better-xcloud#181]
**Platform**
 - Device: Desktop
 - OS: Windows 8
 - Browser: Microsoft edge
 - Browser Version: 109.0.1518.140
 - Better xCloud Version: 2.0.2

My GamePass subscription is not detected by the server when using Better Xcloud and I can only play Fortnite when Better Xcloud is active, but when I disable Better XCLOUD, my GamePass subscription is detected by the server and I can play other games besides Fortnite. I tried disabling and enabling several times to make sure this was a bug, as a result every time I enable Better XCloud, I can't play any other game besides Fortnite. 

**Without Better XCloud**
![Screenshot (262)](https://github.com/redphx/better-xcloud/assets/126675924/33bb6fdc-ef17-4ac9-af5a-9ffc5b41b183)

![Screenshot (261)](https://github.com/redphx/better-xcloud/assets/126675924/f56c39f2-2047-482c-af00-a929627e318b)

**With Better XCloud**
![Screenshot (264)](https://github.com/redphx/better-xcloud/assets/126675924/25845687-c667-4b22-987f-04f97db587e1)

![Screenshot (263)](https://github.com/redphx/better-xcloud/assets/126675924/ddcf9809-7909-45da-8482-ff1452f83cf5)

As you can see there is no gamepass logo on With Better XCloud screenshot

**Comment by redphx** [comment]
Same as this? https://old.reddit.com/r/xcloud/comments/18bqki4/incapable_of_playing_any_game_other_than_fortnite/

**Comment by NasiWaarteG** [comment]
yeah, just like that

**Comment by KingNothing81** [comment]
That's not an issue with the "Better xCloud" script. I also had this yesterday for a while, even when disabling the script in Tampermonkey. The mobile Game Pass Android app was not affected, so I used that for a while. In the meantime the issue has resolved again.

Edit: @NasiWaarteG: Sorry, I missed in your intital post that for you enabling/disabling the script made a difference. Because for me, it didn't. But it really seems that this was not caused by the script and was now solved by Microsoft. If it's still there for you, you might want to try logging out and back in.

**Comment by NasiWaarteG** [comment]
I try to logging out and back in yesterday, and it work for me. I thought that Better XCloud was what made me unable to play other games besides Fortnite and it turned out that the problem came from the server, @KingNothing81 btw, thanks for the info
