### ISSUE TITLE
[Bug] Decode Time value is bugged in Kiwi

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#26]
**Describe the bug**
It makes no sense to me that I got ~30ms decode time in a 60FPS stream, where I got a smooth stream, no lag or frames dropped.  
The stats bar is updated every 1 second, so the decode time should be < 16ms for a 60 FPS stream to have a smooth experience.

**Expected behavior**
Decode time should be < 16ms for a 60 FPS stream.

**Screenshots**
<img width="591" alt="image" src="https://github.com/redphx/better-xcloud/assets/96280/6db99942-f5ab-4ca1-a424-380e41d7b32f">

**Platform (please complete the following information):**
 - OS: Android
 - Browser: Kiwi
 - Browser Version: 116
 - Better xCloud Version: 1.6.2

**Comment by redphx** [comment]
It's definitely bugged in Kiwi. Tested with Firefox Android and the avg decode time is only 1.2ms.

**Comment by sachinpatl** [comment]
On my fire rv stick 4k max -

I think it's not bugged, I have noticed as you lower stream resolution or reduce upscaling the Decode time goes down and the input lag improves as the decode time goes down.

1. 1080p - OpenGL, amd upscaling factor=2, decode time=120+ ms - Not Playable at all
2. 1080p - OpenGL, AMD upscaling factor=0, decode time=80+ ms - Playable but no racing or shooting games 
3. 720p - OpenGL, AMD upscaling factor=2 , decode time = 30+ ms, Very much Playable but still with noticable input lag.

On the other hand the phone and PC is playable even with 1080p Open GL AMD Upscaling=2 because those are very much powerful devices. 

Can we look into using better codec / hw decoding enable option?
So the codec used are not very friendly with the

**Comment by redphx** [comment]
It's bugged because it still shows >20ms on high-end device.  
For Fire Stick, it's too weak to use CAS. Don't bother trying.
