### ISSUE TITLE
[Feature] Automatic Full screen on Kiwi Browser when launching a game

### ISSUE THREAD

**Issue by alecman3000** [redphx/better-xcloud#316]
- Device: Sony Bravia KD-55X75K
- OS: Android TV 11
- Browser: Kiwi Browser 
  
I would like to suggest a feature on Android TV where when you launch a game Kiwi Browser automatically goes to full screen so i can play without seeing the url on the browser.
I don't have a mouse and keyboard and I'm just using the remote and a controller.
In order for me to Fullscreen the game, I have to use tvQuickactions Pro to emulate a mouse using my remote control. But if that's on my controller doesn't work properly in the game as the dpad control changes to moving the browser instead and a and b button doesn't work as confirm and back.
In order for it to work properly i have to disable it from the accessibility settings but switching apps exits the full screen mode for Kiwi Browser.

**Comment by redphx** [comment]
Did you use Kiwi's Desktop mode or change the User-agent?

**Comment by alecman3000** [comment]
> Did you use Kiwi's Desktop mode or change the User-agent?

I didn't use desktop mode. i tried changing user agent but as long as i have tvQuickactions enabled to use my remote as a mouse controller inputs doesn't work properly.

**Comment by KingNothing81** [comment]
@alecman3000: I think we are also having a conversation here on Reddit. ;)
https://www.reddit.com/r/kiwibrowser/comments/19c8ela/have_you_tried_kiwi_browser_on_android_tv/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

All I can say is that when using that mouse app ...
https://github.com/virresh/matvt

... my controller input still works as expected. 

And when the user agent profile is set to default in the script's settings, Kiwi Browser will switch to full screen automatically when starting a game. 

![PNG-Bild](https://github.com/redphx/better-xcloud/assets/146887651/eeb99998-9717-48f2-b909-d138ea009cff)

But this will stop working when you use another UA profile and/or if you request desktop mode.

In Kiwi you request desktop mode by checking a box in Kiwi’s app menu. So please get sure that the box is really not checked when you are on the xCloud website. Otherwise the auto switch to full screen will not work. 
![PNG-Bild 2](https://github.com/redphx/better-xcloud/assets/146887651/a4ec2599-2865-403c-92cf-c20165510422)

**Comment by redphx** [comment]
This is most likely something is wrong with your device
