### ISSUE TITLE
[Bug] [Insider Preview] Notification Button Hides Server Name

### ISSUE THREAD

**Issue by Tak-attack** [redphx/better-xcloud#356]
**Platform**
 - Device: Zenfone 10 and Black Shark 4
 - OS: Android
 - Browser: BX App v0.10.1
 - Better xCloud Version: 3.5.0

**Describe the bug**
The xcloud site accessible via Insider Preview now displays a notification (bell) button in the header, which completely hides the server name. So you cannot open the settings screen.

**Screenshots/Videos**
![Screenshot_20240411-030203_BetterXC](https://github.com/redphx/better-xcloud/assets/149154024/30ae86da-54e7-4dbd-b47c-2ac3ea31a392)

**Comment by KingNothing81** [comment]
I think the problem is that the additional bell icon pushes everything to the right, so the “remote play“ icon will cover the server name.

But talking about the “Insider Preview” I also noticed that there is no “three dot“ menu in the HUD bar anymore. 

![IMG_0251](https://github.com/redphx/better-xcloud/assets/146887651/c72bb2b9-6c7a-4f0c-b2cf-1d8df52bde1b)

I hope @redphx can find another place for the little stream badges that are located there. As I would find it sad to lose them.

**Comment by redphx** [comment]
@Tak-attack @KingNothing81 fixed both issues in 3.5.1

**Comment by KingNothing81** [comment]
@redphx: Thanks for fixing this so quickly. Although I will miss the "Cloud Gaming" logo a little bit, as I sometimes used it to jump back to the xCloud start page. 

And I guess adding back the "three dot menu" will be just a temporary fix. As Microsoft might remove it completely when they roll out the preview to everyone. So how about adding an additional "info" tab to the stream settings (the menu that shows up when you press the gear icon in the HUD bar). And show the infos from the stream badges there?

And with the three dot menu gone someday, maybe the free space could be used to add a "refresh stream" button to the HUD bar. Because as mentioned here ...

https://github.com/redphx/better-xcloud/issues/315

... it's not posssible to do a long press on the red button with remote/controller. So at the moment when I want to do a stream refresh, I force close the app, then open it again and select my currently running game again. This way I can keep my session alive and don't get queued again. But it's not a very comfortable way to do it.
