### ISSUE TITLE
[Bug] Error Interface In My laptop

### ISSUE THREAD

**Issue by MatthiasJethro** [redphx/better-xcloud#399]
### Device

Laptop

### Operating System

Windows

### Browser

Chrome/Edge/Chromium

### Browser Version

124

### Better xCloud Version

4.3.0

### Reproduction Steps

<img width="960" alt="Bugs" src="https://github.com/redphx/better-xcloud/assets/149604071/af902f58-8c7b-491c-9d9f-e60b355b9721">

**Comment by redphx** [comment]
Did you install the script inside Tampermonkey?

**Comment by MatthiasJethro** [comment]
> Did you install the script inside Tampemonkey

Of Course

**Comment by redphx** [comment]
Show screenshots of tampermonkey's dashboard & chrome://extensions

**Comment by MatthiasJethro** [comment]
> Show screenshots of tampermonkey's dashboard & chrome://extensions

<img width="960" alt="and this" src="https://github.com/redphx/better-xcloud/assets/149604071/0eae6e45-b153-481b-bcd2-f6de4bd88abb">
<img width="960" alt="This" src="https://github.com/redphx/better-xcloud/assets/149604071/513cc283-1644-4e89-87e7-254455105a5e">

**Comment by KingNothing81** [comment]
After the last Tampermonkey update, I saw a note in the changelog that it will soon be necessary to enable "developer mode" in the browser for Tampermonkey to continue to work.

See here (changelog for version 5.1.1):

https://www.tampermonkey.net/changelog.php

https://www.tampermonkey.net/faq.php?locale=en#Q209

@redphx: I don't know if this is the reason causing this issue, but it may also be something to keep in mind for future releases when people might open bug reports here because of that change.
