### ISSUE TITLE
[Bug] high decode time

### ISSUE THREAD

**Issue by vresade** [redphx/better-xcloud#413]
### Checklist

- [X] I will only use English in my report.
- [ ] The bug doesn't happen when I disable Better xCloud script.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Device

Desktop

### Device

PC

### Operating System

windows 10

### Browser Version

chrome 124.x

### Better xCloud Version

4.50

### Reproduction Steps

for some reason it's having a very high decode time and i've done everything i know not browser and also the pc has a good performance for cloud gaming i don't know what else to do

**Comment by redphx** [comment]
Try installing older versions

**Comment by KingNothing81** [comment]
I would have a general question regarding decode times: Wouldn't decode times that are too high also lead to dropped frames? So as long as the stream stats don't also show "Lost Frames", can't we just ignore high decode times? Or do the stream stats just show frames that get lost on the way to the client (because of packet loss), but not if they are dropped by the device when decoding the stream?

**Comment by vresade** [comment]
> Tente instalar versões mais antigas

I tried to do that but it was the same thing

**Comment by redphx** [comment]
Then you should check your PC
