### ISSUE TITLE
[Feature] Controller-friendly UI

### ISSUE THREAD

**Issue by redphx** [redphx/better-xcloud#446]
Allows interacting with the Stream settings using only controller, keyboard or remote control

**Comment by redphx** [comment]
Added in 5.4.0

**Comment by KingNothing81** [comment]
Hi ...

Sorry that I'm too late for the release. But I would have two little suggestion for a future release you might like.

- To be able to also close the stream settings with the remote, you could add a "X" (=Close) button in the top right corner of the tabs (beside the question mark). Similiar to how it's like in the Guide menu. Or as an alternative, how about adding an additional close icon at the bottom of the tab selector bar?

- And for those settings that have a list of options you scroll through: Would it be possible to "loop" them? So when you are at the beginning/end of the list and press left/right again, it jumps to the last/first entry. I think this would make adjusting settings with a long list of options more easy. 

Thanks.

**Comment by KingNothing81** [comment]
Hi ...

Thanks again for adding the settings looping.

But one small question: It's supposed to only work in the stream settings at the moment, right? Because it doesn't in the script settings.

But if this doesn't mean a lot of extra work for you and you think it's worth the effort, maybe you could also make it work in the script settings to have a consistent behaviour with the controller-friendly UI.

Thanks.
