### ISSUE TITLE
Better Xcloud 0.17.0 update prompt not going away

### ISSUE THREAD

**Issue by TealDrop** [redphx/better-xcloud#456]
### Checklist

- [X] I will only use English in my report.
- [X] I have used the search function for [**open and closed issues**](https://github.com/redphx/better-xcloud/issues?q=is%3Aissue) to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### Questions

- [ ] xCloud officially supports my country/region.
- [X] The bug doesn't happen when I disable Better xCloud script.
- [X] The bug didn't happen in previous Better xCloud version (name which one).

### Device

Phone/Tablet

### Device

Samsung S23

### Operating System

Android 14

### Android app/Browser Version

Native android app

### Better xCloud Version

Native android app

### Game list

N/A

### Reproduction Steps

Open app. 

Press update. 

Wait for update to finish.

Exit betterxcloud and force stop

Re-open

**Comment by KingNothing81** [comment]
Can you check in your list of installed apps that 0.17.0 was really installed sucessfully?

Because I don't know why but when trying to update to 0.17.0, I had to grant the Better xCloud app the right to install apps from unknown sources again. Without that, the app is not allowed to install apps, so you will be still running the previous version when you start the app. And get the update prompt again.

By the way: If the direct update fails, you can also look for the downloaded APK with a file manager in your device's download folder. And install the update from there. I also do this to delete the downloaded APK files from time to time, as they don't get deleted automatically after updating.

**Comment by TealDrop** [comment]
I randomly saw an updated APK in my recent files section and updated the app with the apk installer and it worked, thank you
